name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set Up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint Python with flake8
      run: |
        pip install flake8
        flake8
    - name: Lint Markdown with MDL
      paths-ignore:
        - '.github/workflows/pull_request_template.md'
      run: |
        sudo gem install mdl
        mdl .